// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe {
	public class Json : global::haxe.lang.HxObject {
		
		public Json(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Json() {
			global::haxe.Json.__hx_ctor_haxe_Json(this);
		}
		
		
		protected static void __hx_ctor_haxe_Json(global::haxe.Json __hx_this) {
		}
		
		
		public static object parse(string text) {
			return global::haxe.format.JsonParser.parse(text);
		}
		
		
		public static string stringify(object @value, global::haxe.lang.Function replacer, string space) {
			return global::haxe.format.JsonPrinter.print(@value, replacer, space);
		}
		
		
	}
}


